
version: 2.1
jobs:
  build-and-test:
    working_directory: /home/
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  
  installaws:
    - run: aws
    - command: apt install awscli -y

sample: 
    jobs:
      - build-and-test
      - installaws
